INSERT INTO "Menu" ("title", "description", "conditions", "person_min", "price_per_person", "remaining_qty", "status", "diet_id", "theme_id", "created_by") VALUES
    ('Menu Prestige Mariage',    'Entrée, plat, fromage et dessert pour un mariage inoubliable',        'Commander au minimum 14 jours avant la prestation.',          50,  85.00,  10, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Mariage'),       (SELECT "id" FROM "User" WHERE "email"='jose@vitegourmand.fr')),
    ('Menu Végétarien Élégant',  'Alternative végétarienne raffinée pour toutes les occasions',         'Commander au minimum 10 jours avant.',                        20,  65.00,  15, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Végétarien'),  (SELECT "id" FROM "Theme" WHERE "name"='Classique'),     (SELECT "id" FROM "User" WHERE "email"='pierre@vitegourmand.fr')),
    ('Cocktail Entreprise',      'Assortiment de canapés et mignardises',                               'Commander au minimum 7 jours avant.',                         30,  45.00,  20, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Entreprise'),    (SELECT "id" FROM "User" WHERE "email"='pierre@vitegourmand.fr')),
    ('Brunch Dominical',         'Viennoiseries, œufs brouillés, fruits frais, jus pressés',            'Commander au minimum 5 jours avant.',                         15,  35.00,  25, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Brunch'),        (SELECT "id" FROM "User" WHERE "email"='sophie@vitegourmand.fr')),
    ('Menu Gastronomique 5 Plats','Expérience culinaire haut de gamme avec accord mets et vins',        'Commander au minimum 21 jours avant. Matériel prêté.',        10, 120.00,   8, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Gastronomique'), (SELECT "id" FROM "User" WHERE "email"='jose@vitegourmand.fr')),
    ('Barbecue Festif',          'Viandes grillées, salades composées, desserts maison',                'Commander au minimum 7 jours avant.',                         25,  40.00,  18, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Barbecue'),      (SELECT "id" FROM "User" WHERE "email"='sophie@vitegourmand.fr')),
    ('Menu Végan Découverte',    'Cuisine 100% végétale créative et savoureuse',                        'Commander au minimum 10 jours avant.',                        15,  55.00,  12, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Végan'),       (SELECT "id" FROM "Theme" WHERE "name"='Événement'),     (SELECT "id" FROM "User" WHERE "email"='pierre@vitegourmand.fr')),
    ('Menu Noël Traditionnel',   'Foie gras, chapon, bûche de Noël — l''esprit des fêtes',             'Commander avant le 15 décembre. Stockage réfrigéré requis.',  30,  95.00,   5, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Noël'),          (SELECT "id" FROM "User" WHERE "email"='jose@vitegourmand.fr')),
    ('Menu Pâques en Famille',   'Agneau de printemps, légumes primeurs, desserts chocolatés',          'Commander avant le 1er avril.',                               20,  70.00,  14, 'published', (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Pâques'),        (SELECT "id" FROM "User" WHERE "email"='sophie@vitegourmand.fr')),
    ('Menu Brouillon Test',      'Ce menu ne devrait pas être visible côté client',                     NULL,                                                          10,  50.00,  99, 'draft',     (SELECT "id" FROM "Diet" WHERE "name"='Classique'),   (SELECT "id" FROM "Theme" WHERE "name"='Classique'),     (SELECT "id" FROM "User" WHERE "email"='jose@vitegourmand.fr'));
